name: AWS EC2 deployment test

on: 
  push:
    branches:
      - main

jobs:
  deployment:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Get dependencies cache directory
        id: dep-cache
        shell: bash
        run: |
          echo "STORE_PATH=$(cache path)" >> $GITHUB_OUTPUT

      - name: Setup npm cache
        uses: actions/cache@v3
        with:
          path: ${{ steps.dep-cache.outputs.STORE_PATH }}
          key: ${{ runner.os }}-dep-store-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-dep-store-

      - name: Install dependencies
        run: npm ci

      - name: Build application
        run: npm run build

      - name: Create .pem
        run: |
          echo "$SSH_PEM_KEY" >> $HOME/su-test.pem
          chmod 400 $HOME/su-test.pem
        env:
          SSH_PEM_KEY: ${{ secrets.AWS_SSH_KEY }}

      - name: Connet EC2 by SSH
        run: |
          ssh -i $HOME/su-test.pem ${SSH_USER}@${SSH_HOSTNAME}
        env:
          SSH_USER: ${{ secrets.EC2_USER }}
          SSH_HOSTNAME: ${{ secrets.EC2_HOSTNAME }}

      # - name: Configure AWS credentials
      #   uses: aws-actions/configure-aws-credentials@v1
      #   with:
      #     aws-access-key-id: ${{ secrets.EC2_ACCESS_ID }}
      #     aws-secret-access-key: ${{ secrets.EC2_ACCESS_SECRET_KEY }}
      #     aws-region: ${{ secrets.EC2_REGION }}
